### ISSUE TITLE
I want to know the right way to integrate hawk

### ISSUE THREAD

**Issue by Y-k-Y** [codex-team/hawk.javascript#85]
Hello, I'm newbie at CodeX.

I want to know what is the right way to integrate hawk.
I followed installation guide on the hawk garage and also on the readme several times but it seems none of them are works for me.
Or it just isn't showed up on hawk garage? 
I have checked that i can make manual error message by hawk and i see the error log on the browser console as below.

![image](https://user-images.githubusercontent.com/40556882/150161130-db7ca195-e526-46fd-a1f9-80b22f59bfdb.png)

But my garage keep saying that no one catcher connected and showing up the catalog of catchers.

**Comment by neSpecc** [comment]
Could you show the Response?

**Comment by Y-k-Y** [comment]
Oh sorry never mind. 
It seems that it needs some time to collect error logs to display at garage? Now it shows me my error logs.
